name: REDF CI
on:
  pull_request:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['ros:humble-ros-base', 'ros:iron-ros-base']
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v3
    - name: Install rustup dependencies
      run: |
        apt update
        apt install -y curl
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: rosdep
      run: |
        apt update && apt upgrade -y
        rosdep update
        rosdep resolve -q ament_cmake std_msgs example_interfaces | sed '/^#/d' | xargs sudo apt install -y
    - name: cargo test
      run: . /ros_entrypoint.sh && cargo test
