on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: [ros:humble-ros-core]
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - name: test
      run: cargo test
