name: REDF CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup colcon workspace
      id: configure
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt update -qq
        apt install -qq -y lsb-release wget curl gnupg2
        cd ..
        mkdir -p /home/src
        cp -r redf /home/src/
        sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
        apt-get update && apt-get upgrade -q -y
        apt-get update && apt-get install -qq -y \
          dirmngr \
          gnupg2 \
          lsb-release \
          python3-colcon-ros \
          python3-colcon-common-extensions \
          python3-rosdep \
          build-essential \
          cargo \
          rust-all
        cd /home/src/redf/tests
        rosdep init
        rosdep update
        rosdep install --from-paths ./ -i -y --rosdistro rolling
    - name: Build project
      id: build
      run: |
        cd /home/src/redf
        cargo build
    - name: Run tests
      id: test
      run: |
        cd /home/src/redf
        cargo test
